<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iot" nsURI="https://org.cea.architecture/iot" nsPrefix="iot">
  <eClassifiers xsi:type="ecore:EClass" name="IotDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectivity" eType="#//CommunicationProtocol"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gateway" eType="#//EdgeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//IotDevice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ActuatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//IotDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//SensorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationProtocol" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ethernet" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Serial" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wifi" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bluetooth" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Zigbee" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="KNX" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoRa" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="SixLoWPAN" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="ZWave" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnOcean" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="RFID" eSuperTypes="#//CommunicationProtocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subregion" upperBound="-1"
        eType="#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processor" eType="#//Processor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedNodes" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" eType="#//RootState"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//IotDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FogNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="CloudNode" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Processor">
    <eLiterals name="x86" value="1"/>
    <eLiterals name="arm" value="2"/>
    <eLiterals name="x64" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ServiceKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceKind">
    <eLiterals name="RemotePatientMonitoring"/>
    <eLiterals name="InfusionPump" value="1"/>
    <eLiterals name="StresssMonitoring" value="2"/>
    <eLiterals name="OxigenLevelMonitoring" value="3"/>
    <eLiterals name="HeartRateMonitory" value="4"/>
    <eLiterals name="GlucoseMonitoryng" value="5"/>
    <eLiterals name="ThermometersMonitoring" value="6"/>
    <eLiterals name="DataStorage" value="7"/>
    <eLiterals name="DataAnalysis" value="8"/>
    <eLiterals name="EmergencyResponse" value="9"/>
    <eLiterals name="VoiceBasedHealthAssitants" value="10"/>
    <eLiterals name="SurgicalNavigation" value="11"/>
    <eLiterals name="MedicalImageAnalysis" value="12"/>
    <eLiterals name="IoMTCybersecurity" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Information" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//InformationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="record" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InformationKind">
    <eLiterals name="PatientPersonalData"/>
    <eLiterals name="PatientHealthRecords" value="1"/>
    <eLiterals name="RealTimePatientData" value="2"/>
    <eLiterals name="InsuranceAndBilling" value="3"/>
    <eLiterals name="DeviceSensorData" value="4"/>
    <eLiterals name="StaffUserData" value="5"/>
    <eLiterals name="ThirdPartyData" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntangileAsset" eSuperTypes="#//Asset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//IntangibleAssetKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntangibleAssetKind">
    <eLiterals name="HospitalReputation"/>
    <eLiterals name="IoMTBrandEquity" value="1"/>
    <eLiterals name="PatientSatisfaction" value="2"/>
    <eLiterals name="DataPrivacySecurityTrust" value="3"/>
    <eLiterals name="IntellectualProperty" value="4"/>
    <eLiterals name="Licences" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootState" eSuperTypes="#//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substate" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internal" upperBound="-1"
        eType="#//InternalTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Handler" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalTransition" eSuperTypes="#//Handler"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveMessage" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionBlock" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternStatement" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalVariable" eSuperTypes="#//Variable #//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignment" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Increment" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decrement" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="#//PropertyReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseAction" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exp" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" upperBound="-1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCallStatement" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventReference" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveMsg" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCallExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//AbstractConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propassigns" upperBound="-1"
        eType="#//ConfigPropertyAssign" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//IotDevice"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigPropertyAssign">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//PlatformAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConnector" eSuperTypes="#//NamedElement #//AnnotatedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//PlatformAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardinality" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//TypeRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//AbstractConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cli" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" eType="#//RequiredPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srv" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provided" eType="#//ProvidedPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//NamedElement #//AnnotatedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sends" unique="false" upperBound="-1"
        eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receives" unique="false"
        upperBound="-1" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalConnector" eSuperTypes="#//AbstractConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inst" eType="#//Instance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlatformAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
